[versions]
retrofit2 = "3.0.0"
jjwt = "0.13.0"
jackson = "2.20.1"
jackson-annotations = "2.20"
assertj = "3.27.6"
junit = "6.0.1"
junitPlatformLauncher = "6.0.1"
slf4j = "2.0.17"
mockito = "5.21.0"
okhttp3 = "5.3.2"

[libraries]
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit2" }
system-lambda = { group = "com.github.stefanbirkner", name = "system-lambda", version = "1.2.1" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.22" }

okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }

javax-annotation = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }

jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version = "6.1.0" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version = "3.0.0" }

# logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }

# tests
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }
jsonassert = { module = "org.skyscreamer:jsonassert", version = "1.5.3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
wiremock = { group = "org.wiremock", name = "wiremock-standalone", version = "3.13.2" }
socks-proxy-server = { module = "com.github.bbottema:java-socks-proxy-server", version = "4.1.2" }
littleproxy = { module = "io.github.littleproxy:littleproxy", version = "2.4.6" }

[bundles]
retrofit2 = ["retrofit2-converter-jackson", "retrofit2-retrofit"]
tests = [
    "assertj-core",
    "junit-jupiter-api", "junit-jupiter-params", "junit-jupiter-engine", "junit-platform-launcher",
    "slf4j-api", "logback",
    "mockito-core", "mockito-junit-jupiter",
]
